# Limpieza de Datos

## Análisis Exploratorio

In [1]:
import pandas as pd
import os

In [2]:
archivo = "GSAF5.xls"

In [3]:
if os.path.exists(archivo):
    df = pd.read_excel(archivo)
    print("¡Archivo cargado!")
    display(df.head())
else:
    print(f"Error: No se encontró el archivo '{archivo}' en el directorio actual.")

¡Archivo cargado!

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,29th January,2026.0,Unprovoked,Brazil,Recife,Del Chifre Beach in Olinda,Swimming,Deivson Rocha Dantas,M,13,...,Unknown bull and tiger sharks frequent the area,Kevin McMurray Trackingsharks.com: TV Globo: P...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,29th January,2026.0,Unprovoked,Australia,NSW,Angels Beach East Ballina,Surfing,Unnamed man,M,?,...,Unknown,Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,24th January,2026.0,Unprovoked,Australia,Tasmania,Cooee Beach west of Burnie,Swimming,Megan Stokes,F,?,...,1.7m Seven Gill shark,Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20th January,2026.0,Unprovoked,Australia,NSW,Point Plomber North of Port Macquarie,Surfing,Paul Zvirdinas,M,39,...,Bull shark,Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,19th January,2026.0,Unprovoked,Australia,NSW,Dee Why,Surfing,Unknown,M,11,...,Bull shark,Andy Currie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Establezco el límite de columnas mostradas
pd.set_option('display.max_columns', None)
df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,29th January,2026.0,Unprovoked,Brazil,Recife,Del Chifre Beach in Olinda,Swimming,Deivson Rocha Dantas,M,13,Right thigh and lower leg stripped of flesh,Y,?,Unknown bull and tiger sharks frequent the area,Kevin McMurray Trackingsharks.com: TV Globo: P...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,29th January,2026.0,Unprovoked,Australia,NSW,Angels Beach East Ballina,Surfing,Unnamed man,M,?,No injury shark knocked man of his board,N,1100hrs,Unknown,Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,24th January,2026.0,Unprovoked,Australia,Tasmania,Cooee Beach west of Burnie,Swimming,Megan Stokes,F,?,Puncture wounds to right knee,N,1815hrs,1.7m Seven Gill shark,Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20th January,2026.0,Unprovoked,Australia,NSW,Point Plomber North of Port Macquarie,Surfing,Paul Zvirdinas,M,39,Minor cuts and abrasions,N,0830hrs,Bull shark,Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,19th January,2026.0,Unprovoked,Australia,NSW,Dee Why,Surfing,Unknown,M,11,None reported damage to board,N,1145hrs,Bull shark,Andy Currie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7074 entries, 0 to 7073
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            7074 non-null   object
 1   Year            7072 non-null   float64
 2   Type            7056 non-null   str
 3   Country         7024 non-null   str
 4   State           6587 non-null   str
 5   Location        6507 non-null   str
 6   Activity        6491 non-null   str
 7   Name            6856 non-null   str
 8   Sex             6496 non-null   str
 9   Age             4080 non-null   object
 10  Injury          7039 non-null   str
 11  Fatal Y/N       6513 non-null   object
 12  Time            3547 non-null   object
 13  Species         3943 non-null   str
 14  Source          7054 non-null   object
 15  pdf             6799 non-null   object
 16  href formula    6794 non-null   str
 17  href            6796 non-null   str
 18  Case Number     6798 non-null   str
 19  Case Number.1   6797 non-null   str
 20  original order  6799 non-null   float64
 21  Unnamed: 21     1 non-null      str
 22  Unnamed: 22     2 non-null      str
dtypes: float64(2), object(6), str(15)
memory usage: 1.2+ MB

## Limpieza

In [6]:
# Elimino columnas con casi todo nulos
df1 = df.drop(columns=['Unnamed: 21', 'Unnamed: 22'])

Veamos la cantidad de nulos por campo.

In [7]:
df1.isnull().sum().sort_values(ascending=False)

Time              3527
Species           3131
Age               2994
Activity           583
Sex                578
Location           567
Fatal Y/N          561
State              487
href formula       280
href               278
Case Number.1      277
Case Number        276
pdf                275
original order     275
Name               218
Country             50
Injury              35
Source              20
Type                18
Year                 2
Date                 0
dtype: int64

Se observan campos con gran cantidad de nulos, aunque no serían los de mayor interés para el análisis actual.
Seguidamente analizamos porcentualmente la incidencia de nulos para saber el impacto en el error que pudiera introducir debido a información faltante.

In [8]:
# Porcentaje de nulos por columna
porcentaje_nulos = (df1.isnull().sum() / len(df1)) * 100
print(porcentaje_nulos.sort_values(ascending=False))

Time              49.858637
Species           44.260673
Age               42.324003
Activity           8.241448
Sex                8.170766
Location           8.015267
Fatal Y/N          7.930450
State              6.884365
href formula       3.958157
href               3.929884
Case Number.1      3.915748
Case Number        3.901612
pdf                3.887475
original order     3.887475
Name               3.081708
Country            0.706814
Injury             0.494770
Source             0.282725
Type               0.254453
Year               0.028273
Date               0.000000
dtype: float64

Afortunadamente, el impacto en los campos de mayor interés (Country y Type) es mínimo.

### Campo Year

In [9]:
# Convertir a entero 
df1['Year'] = df1['Year'].astype('Int64')
df1[['Year']].head()

   Year
0  2026
1  2026
2  2026
3  2026
4  2026

Ahora analizamos posibles años extraños o cargados con error.

In [10]:
df1[df1['Year'] < 1500][['Country','Type','Location','Year']]

,Country,Type,Location,Year
6942,USA,Unprovoked,Archeological site,1000
6943,NaN,Unprovoked,NaN,77
6944,AUSTRALIA,Unprovoked,Bondi,5
6945,NaN,Unprovoked,NaN,0
6946,GREECE,Unprovoked,In the haven of Cantharus,0
...,...,...,...,...
7069,AUSTRALIA,Unprovoked,Roebuck Bay,0
7070,AUSTRALIA,Unprovoked,NaN,0
7071,USA,Unprovoked,Ocracoke Inlet,0
7072,PANAMA,Unprovoked,"Panama Bay 8ºN, 79ºW",0
7073,CEYLON (SRI LANKA),Unprovoked,"Below the English fort, Trincomalee",0

### Campo Country
Será necesario eliminar los Country='NaN'

In [11]:
# Borrar filas donde la columna Country sea nula
df1.dropna(subset=['Country'], inplace=True)

De igual manera procedemos con campo 'Type' cuya baja incidencia de NaN lo hace posible.

In [12]:
# Quitar espacios al en los extremos y poner primera letra en mayúsculas
df1['Country'] = df1['Country'].str.strip().str.capitalize()

In [13]:
# Vemos los 20 Country más frecuentes
print(df1['Country'].value_counts().head(20))

Country
Usa                 2579
Australia           1523
South africa         599
New zealand          146
Bahamas              141
Papua new guinea     136
Brazil               123
Mexico               107
Italy                 72
Fiji                  70
New caledonia         67
Philippines           65
Reunion               60
Egypt                 53
Mozambique            50
Cuba                  49
Spain                 47
India                 41
French polynesia      40
Japan                 36
Name: count, dtype: int64

### Campo Type
La tabla top anterior luce bien en cuanto a los principales países.

In [14]:
# Borrar filas donde la columna Type sea nula
df1.dropna(subset=['Type'], inplace=True)

In [15]:
# Quitar espacios al en los extremos y poner primera letra en mayúsculas
df1['Type'] = df1['Type'].str.strip().str.capitalize()

In [16]:
# Vemos los Type más frecuentes
print(df1['Type'].value_counts().head(20))

Type
Unprovoked             5193
Provoked                641
Invalid                 547
Watercraft              354
Sea disaster            234
Questionable             26
Boat                      7
?                         1
Unconfirmed               1
Unverified                1
Under investigation       1
Name: count, dtype: int64

Consideramos Boat como Watercraft

In [17]:
# Unificar Boat en Watercraft
df1['Type'] = df1['Type'].replace('Boat', 'Watercraft')

Ahora los casos con frecuencia 1 y etiquetas dudosas

In [18]:
# Contamos las frecuencias
counts = df1['Type'].value_counts()

In [19]:
counts

Type
Unprovoked             5193
Provoked                641
Invalid                 547
Watercraft              361
Sea disaster            234
Questionable             26
?                         1
Unconfirmed               1
Unverified                1
Under investigation       1
Name: count, dtype: int64

Eliminamos los casos de una sola aparición o irrelevantes

In [20]:
# Lista de tipos que queremos eliminar 
tipos_a_borrar = ['?', 'Unconfirmed', 'Unverified', 'Under investigation']

# Filtrar: Nos quedamos con todo lo que NO esté en esa lista
df = df1[~df1['Type'].isin(tipos_a_borrar)]

# Verificamos el resultado final
print(df['Type'].value_counts())

Type
Unprovoked      5193
Provoked         641
Invalid          547
Watercraft       361
Sea disaster     234
Questionable      26
Name: count, dtype: int64

### Campos Age, Sex, Fatal

In [21]:
# Los campos de interés
cols_to_fix = ['Sex', 'Fatal Y/N', 'Age']

# Limpiar espacios y pasar a mayúsculas
for col in cols_to_fix:
    df[col] = df[col].astype(str).str.strip().str.upper()

In [22]:
df['Sex'].value_counts()

Sex
M        5621
F         803
LLI         1
?           1
M X 2       1
N           1
.           1
Name: count, dtype: int64

In [23]:
# Imputación directa (M X 2 y N pasan a M)
df['Sex'] = df['Sex'].replace(['M X 2', 'N'], 'M')

In [24]:
# Imputación directa del resto
df['Sex'] = df['Sex'].replace(['LLI'], 'F')
df['Sex'] = df['Sex'].replace(['?','.'], 'M')

In [25]:
df['Sex'].value_counts()

Sex
M    5625
F     804
Name: count, dtype: int64

Ahora Age

In [26]:
print(df['Age'].value_counts().to_string())

Age
17                         173
18                         160
15                         157
20                         154
19                         152
16                         151
21                         130
22                         125
25                         119
14                         118
24                         115
13                         108
26                         102
23                          90
30                          88
29                          88
12                          87
28                          87
27                          86
32                          82
35                          79
40                          65
10                          65
38                          60
31                          59
34                          55
37                          49
42                          49
36                          49
33                          49
43                          49
11                          46
9                           45
41                          45
39                          44
45                          42
50                          41
52                          40
46                          36
8                           35
49                          35
48                          33
47                          33
44                          32
55                          30
57                          28
7                           28
51                          27
58                          23
60                          23
54                          21
?                           19
56                          17
61                          17
59                          17
53                          17
6                           16
TEEN                        15
62                          13
69                          12
30S                         12
63                          11
68                          11
64                          10
20S                         10
70                          10
66                           9
65                           9
5                            7
50S                          6
73                           5
40S                          5
3                            5
77                           4
71                           4
75                           4
                             4
67                           3
60S                          3
74                           3
4                            2
8 OR 10                      2
1                            2
7 OR 8                       2
78                           2
YOUNG                        2
50+                          1
85                           1
30+                          1
40+                          1
60+                          1
MIDDLE AGE                   1
20/30                        1
!2                           1
M                            1
!6                           1
!!                           1
45 AND 15                    1
28 & 22                      1
22, 57, 31                   1
20'S                         1
9 & 60                       1
A MINOR                      1
82                           1
40?                          1
72                           1
18 MONTHS                    1
28 & 26                      1
86                           1
18 OR 20                     1
12 OR 13                     1
46 & 34                      1
28, 23 & 30                  1
TEENS                        1
36 & 26                      1
84                           1
30 OR 36                     1
6½                           1
21 & ?                       1
33 OR 37                     1
MID-30S                      1
23 & 20                      1
7      &    31               1
20?                          1
60'S                         1
32 & 30                      1
16 TO 18                     1
87                           1
ELDERLY                      1
MID-20S                      1
CA. 33                       1
21 OR 26                     1
>50                          1
18 TO 22                     1
ADULT                        1
9 & 12                       1
? & 19                       1
9 MONTHS                     1
25 TO 35                     1
23 & 26                      1
(ADULT)                      1
33 & 37                      1
25 OR 28                     1
37, 67, 35, 27,  ? & 27      1
21, 34,24 & 35               1
30 & 32                      1
50 & 30                      1
17 & 35                      1
X                            1
"MIDDLE-AGE"                 1
13 OR 18                     1
34 & 19                      1
33 & 26                      1
2 TO 3 MONTHS                1
MAKE LINE GREEN              1
81                           1
"YOUNG"                      1
17 & 16                      1
F                            1
BOTH 11                      1
9 OR 10                      1
36 & 23                      1
A.M.                         1
?    &   14                  1
10 OR 12                     1
31 OR 33                     1
2½                           1
13 OR 14                     1

In [27]:
# Limpieza básica
from clean_age import clean_age

df['Age2'] = df['Age'].apply(clean_age)

In [28]:
print(df['Age2'].value_counts().to_string())

Age2
17                         173
15                         173
18                         160
20                         157
19                         152
16                         151
21                         130
22                         125
25                         119
14                         118
24                         115
13                         108
26                         102
30                          90
23                          90
12                          88
29                          88
28                          87
27                          86
32                          82
35                          79
40                          65
10                          65
38                          60
31                          59
34                          55
37                          49
42                          49
36                          49
33                          49
43                          49
11                          46
9                           45
41                          45
39                          44
45                          44
50                          41
52                          40
46                          36
8                           35
49                          35
48                          33
47                          33
44                          32
55                          30
57                          28
7                           28
51                          27
58                          23
60                          23
54                          21
56                          17
61                          17
59                          17
53                          17
6                           16
62                          13
69                          12
30S                         12
63                          11
68                          11
70                          11
64                          10
20S                         10
66                           9
65                           9
5                            7
50S                          6
73                           5
40S                          5
3                            5
77                           4
71                           4
75                           4
                             4
67                           3
60S                          3
74                           3
4                            2
8 OR 10                      2
1                            2
7 OR 8                       2
78                           2
50+                          1
85                           1
30+                          1
40+                          1
60+                          1
20/30                        1
!2                           1
M                            1
!6                           1
45 AND 15                    1
28 & 22                      1
22, 57, 31                   1
20'S                         1
9 & 60                       1
82                           1
40?                          1
72                           1
18 MONTHS                    1
28 & 26                      1
86                           1
18 OR 20                     1
12 OR 13                     1
46 & 34                      1
28, 23 & 30                  1
36 & 26                      1
84                           1
30 OR 36                     1
6½                           1
21 & ?                       1
33 OR 37                     1
MID-30S                      1
23 & 20                      1
7      &    31               1
20?                          1
60'S                         1
32 & 30                      1
16 TO 18                     1
87                           1
MID-20S                      1
CA. 33                       1
21 OR 26                     1
>50                          1
18 TO 22                     1
9 & 12                       1
? & 19                       1
9 MONTHS                     1
25 TO 35                     1
23 & 26                      1
33 & 37                      1
25 OR 28                     1
37, 67, 35, 27,  ? & 27      1
21, 34,24 & 35               1
30 & 32                      1
50 & 30                      1
17 & 35                      1
13 OR 18                     1
34 & 19                      1
33 & 26                      1
2 TO 3 MONTHS                1
81                           1
17 & 16                      1
F                            1
BOTH 11                      1
9 OR 10                      1
36 & 23                      1
?    &   14                  1
10 OR 12                     1
31 OR 33                     1
2½                           1
13 OR 14                     1

Si bien ha mejorado mucho, no se pudieron estandarizar todos los casos todavía, aunque no es un campo principal para nuestro análisis está claro que tiene muchos errores de carga manual y falta de criterio.

## Cantidad de Incidentes por Tipo y País

In [29]:
# Agrupamos por País y Tipo de ataque
df_tipo_pais = df.groupby(['Country', 'Type']).size().reset_index(name='Incident_Count').sort_values(by='Incident_Count', ascending=False)
df_tipo_pais.head(10)

              Country        Type  Incident_Count
430               Usa  Unprovoked            2011
22          Australia  Unprovoked            1098
361      South africa  Unprovoked             415
427               Usa    Provoked             238
426               Usa     Invalid             195
19          Australia    Provoked             144
23          Australia  Watercraft             128
18          Australia     Invalid             120
307  Papua new guinea  Unprovoked             112
31            Bahamas  Unprovoked             109

In [30]:
# Pivot
tabla_pivot = df_tipo_pais.pivot(index='Country', columns='Type', values='Incident_Count').fillna(0)

display(tabla_pivot)

Type,Invalid,Provoked,Questionable,Sea disaster,Unprovoked,Watercraft
Country,,,,,,
Admiralty islands,0.0,0.0,0.0,0.0,1.0,0.0
Africa,0.0,0.0,0.0,0.0,1.0,0.0
Algeria,0.0,0.0,0.0,0.0,1.0,0.0
American samoa,0.0,0.0,0.0,0.0,3.0,0.0
Andaman / nicobar islandas,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...
Venezuela,0.0,0.0,0.0,0.0,11.0,0.0
Vietnam,0.0,1.0,0.0,1.0,12.0,0.0
West indies,0.0,0.0,0.0,0.0,2.0,0.0
Western samoa,0.0,0.0,0.0,0.0,1.0,0.0
Yemen,1.0,0.0,0.0,1.0,7.0,0.0

In [31]:
# Creamos un pivot table
tabla_pivot = df_tipo_pais.pivot(index='Country', columns='Type', values='Incident_Count').fillna(0)

# Calculamos la columna 'Total' sumando todas las columnas de tipos
tabla_pivot['Total'] = tabla_pivot.sum(axis=1)

# Ahora ordenamos por la columna 'Total'
tabla_pivot = tabla_pivot.sort_values(by='Total', ascending=False)

# Convertimos a entero para mejor visual
tabla_pivot = tabla_pivot.astype(int)

display(tabla_pivot.head(10))

Type,Invalid,Provoked,Questionable,Sea disaster,Unprovoked,Watercraft,Total
Country,,,,,,,
Usa,195,238,7,35,2011,83,2569
Australia,120,144,6,24,1098,128,1520
South africa,65,58,0,5,415,55,598
New zealand,13,21,0,0,95,17,146
Bahamas,5,18,2,5,109,1,140
Papua new guinea,2,13,0,6,112,3,136
Brazil,10,6,0,5,102,0,123
Mexico,11,12,4,3,74,3,107
Italy,12,13,0,4,27,16,72
Fiji,1,3,1,3,61,1,70

## Exportación de resultados

In [32]:
# Preparar para exportar
tabla_final_export = tabla_pivot.reset_index()
tabla_final_export.to_csv('mapa_ataques_tiburones.csv', index=False)

## Visualización de Resultados

In [33]:
import plotly.express as px

In [34]:
fig = px.choropleth(tabla_final_export, 
                    locations="Country", 
                    locationmode='country names',
                    color="Total", 
                    hover_name="Country", 
                    # Usamos una escala de colores rojos
                    color_continuous_scale=px.colors.sequential.Reds,
                    title='Distribución Global de Ataques de Tiburón (Total)')

fig.update_layout(margin={"r":0,"t":50,"l":0,"b":0})
fig.show()

/tmp/ipykernel_2816230/3820440534.py:1: DeprecationWarning: The library used by the *country names* `locationmode` option is changing in an upcoming version. Country names in existing plots may not work in the new version. To ensure consistent behavior, consider setting `locationmode` to *ISO-3*.
  fig = px.choropleth(tabla_final_export,

In [ ]:
# Guardar como PNG
fig.write_image("mapa_ataques_tiburones.png", width=1200, height=800, scale=2)

# Guardar como SVG (vectorial)
fig.write_image("mapa_ataques_tiburones.svg")

¡Mapa exportado con éxito!